Upgrade/Add BSON dependency
mongodb-js/mongodb-mock-server pull request #2
Opened 2020-03-10 21:05 UTC by nbbeeken

## Upgrade BSON Dependency
https://jira.mongodb.org/browse/NODE-2491

2020-03-10 21:17 UTC, mbroadst requested changes

2020-03-10 21:17 UTC, mbroadst commented on lib/server.js
> +    this.bson = BSON;
If we're moving forward with a hard dependency on BSONv4, then I think the refactor here should be more complete. I think you can remove `this.bson` here, and just import `BSON` directly in `protocol.js`

2020-03-12 14:56 UTC, nbbeeken commented
RFAL

2020-03-12 16:41 UTC, mbroadst approved these changes
LGTM

2020-03-12 17:26 UTC, merged